---

- name: Install kafka
  include: build.yml
  tags:
    - build

- name: Install kafka
  include: configure.yml
  tags:
    - configure

- name: Install kafka Manager
  include: manager.yml
  tags:
    - manager
